#include <stdio.h>
#include <stdlib.h>

#include "normal.h"

int main() {
  int no_schools = 25;
  int no_students_per_school = 4;
  int school_capacity = 5;
  double school_valence_std_dev = 1.0;
  double idiosyncratic_std_dev = 1.0;
  
  int i, j, k;
  
  int no_students = no_schools * no_students_per_school;
  double* location = malloc(no_students * sizeof(double));
  for (i = 1; i <= no_students; i++) {
    location[i-1] = (double)i/no_students_per_school;
  }

  double** distance = malloc(no_students * sizeof(double*));
  for (i = 1; i <= no_students; i++) {
    distance[i-1] = malloc(no_schools * sizeof(double));
    for (j = 1; j <= no_schools; j++) {
      double a = location[i-1];
      double b = (double)j;
      double c = (double)no_schools;
      distance[i-1][j-1] = min(min(fabs(a - b), fabs(a - b - c)),fabs(a - b + c));
    }
  }
  
  double* valence = malloc(no_schools * sizeof(double));
  for (j = 1; j <= no_schools; j++) {
    valence[j-1] = school_valence_std_dev * normal();
  }

  double** utility = malloc(no_students * sizeof(double*));
  for (i = 1; i <= no_students; i++) {
    utility[i-1] = malloc(no_schools * sizeof(double));
    for (j = 1; j <= no_schools; j++) {
      utility[i-1][j-1] = valence[j-1] + idiosyncratic_std_dev * normal() - distance[i-1][j-1];
    }
  }

  int* safe_school = malloc(no_students * sizeof(int));
  i = 1;
  safe_school[i-1] = no_schools;
  while (2 * i < no_students_per_school) {
    i++;
    safe_school[i-1] = no_schools;
  }
  for (j = 1; j < no_schools; j++) {
    for (k = 1; k <= no_students_per_school; k++) {
      i++;
      safe_school[i-1] = j;
    }
  }
  while (i < no_students) {
    i++;
    safe_school[i-1] = no_schools;
  }

  int** priority = malloc(no_students * sizeof(int*));
  int* no_ranked_schools = malloc(no_students * sizeof(int));
  for (i = 1; i <= no_students; i++) {
    priority[i-1] = malloc(no_schools * sizeof(int));
    no_ranked_schools[i-1] = 0;
    for (j = 1; j <= no_schools; j++) {
      if (utility[i-1][safe_school[i-1] - 1] <= utility[i-1][j-1]) {
	priority[i-1][j-1] = 1;
	no_ranked_schools[i-1]++;
      }
      else {
	priority[i-1][j-1] = 0;
      }
    }
  }

  int** preferences = malloc(no_students * sizeof(int*));
  for (i = 1; i <= no_students; i++) {
    preferences[i-1] = malloc(no_ranked_schools[i-1] * sizeof(int));
    int no_already_ranked = 0;
    for (j = 1; j <= no_schools; j++) {
      if (utility[i-1][safe_school[i-1] - 1] <= utility[i-1][j-1]) {
	if (no_already_ranked == 0) {
	  preferences[i-1][0] = j;
	  no_already_ranked = 1;
	}
	else {
	  k = no_already_ranked;
	  while (utility[i-1][j-1] > utility[i-1][preferences[i-1][k-1]-1] && k > 0) {
	    preferences[i-1][k] = preferences[i-1][k-1];  /* Oh no! Bubble sort */
	    k--;
	  }
	  preferences[i-1][k] = j;
	  no_already_ranked++;
	}
      }
    }
  }


  printf("/* This file was generated by make_ex with %i schools, %i students per school, capacity %i for all\n", no_schools, no_students_per_school, school_capacity);
  printf("schools, school valence standard deviation %1.2f, and idiosyncratic standard deviation %1.2f. */\n",school_valence_std_dev,idiosyncratic_std_dev);
  printf("There are %i students and %i schools\n",no_students,no_schools);
  printf("The vector of quotas is (");
  for (j = 1; j < no_schools; j++) {
    printf("%i,",school_capacity);
  }
  printf("%i)\n",school_capacity);
  printf("The priority matrix is\n");
  for (i = 1; i <= no_students; i++) {
    for (j = 1; j <= no_schools; j++) {
      printf("    %i",priority[i-1][j-1]);
    }
    printf("\n");
  }
  printf("The students numbers of ranked schools are\n(");
  for (i = 1; i < no_students; i++) {
    printf("%i,",no_ranked_schools[i-1]);
  }
  printf("%i)\n",no_ranked_schools[no_students - 1]);
  printf("The preferences of the students are");
  for (i = 1; i <= no_students; i++) {
    printf("\n%i:",i);
    if (i < 10) {
      printf(" ");
    }
    for (k = 1; k <= no_ranked_schools[i-1]; k++) {
      printf("   %i",preferences[i-1][k-1]);
    }
  }
  printf("\nThe priority thresholds of the schools are\n");
  for (j = 1; j <= no_schools; j++) {
    printf("1   ");
  }
  printf("\n");

  
  return 0;
}
